%% 自動生成 (dag/report.pl) — QRN 主張依存グラフ
graph BT
  QRN_C0_001["QRN-C0-001 (c0)"]:::c0
  QRN_C0_002["QRN-C0-002 (c0)"]:::c0
  QRN_C0_003["QRN-C0-003 (c0)"]:::c0
  QRN_C0_004["QRN-C0-004 (c0)"]:::c0
  QRN_C0_005["QRN-C0-005 (c0)"]:::c0
  QRN_C0_006["QRN-C0-006 (c0)"]:::c0
  QRN_QM_001["QRN-QM-001 (c1)"]:::c1
  QRN_GR_001["QRN-GR-001 (c1)"]:::c1
  QRN_STAT_001["QRN-STAT-001 (c1)"]:::c1
  QRN_FIELD_001["QRN-FIELD-001 (c1)"]:::c1
  QRN_GAUGE_001["QRN-GAUGE-001 (c1)"]:::c1
  QRN_ENT_001["QRN-ENT-001 (c1)"]:::c1
  QRN_GEOM_001["QRN-GEOM-001 (c1)"]:::c1
  QRN_GEOM_002["QRN-GEOM-002 (c1)"]:::c1
  QRN_GEOM_003["QRN-GEOM-003 (c3)"]:::c3
  QRN_GRAV_001["QRN-GRAV-001 (c1)"]:::c1
  QRN_GRAV_002["QRN-GRAV-002 (c1)"]:::c1
  QRN_BH_001["QRN-BH-001 (c1)"]:::c1
  QRN_CAUSAL_001["QRN-CAUSAL-001 (c1)"]:::c1
  QRN_CAUSAL_002["QRN-CAUSAL-002 (c3)"]:::c3
  QRN_ER_001["QRN-ER-001 (c3)"]:::c3
  QRN_QEC_001["QRN-QEC-001 (c1)"]:::c1
  QRN_GAUGE_002["QRN-GAUGE-002 (c1)"]:::c1
  QRN_COSMO_001["QRN-COSMO-001 (c1)"]:::c1
  QRN_COSMO_002["QRN-COSMO-002 (c4)"]:::c4
  QRN_COSMO_003["QRN-COSMO-003 (c3)"]:::c3
  QRN_BORN_001["QRN-BORN-001 (c1)"]:::c1
  QRN_BORN_002["QRN-BORN-002 (c1)"]:::c1
  QRN_GRAV_003["QRN-GRAV-003 (c1)"]:::c1
  QRN_KK_001["QRN-KK-001 (c1)"]:::c1
  QRN_MATTER_001["QRN-MATTER-001 (c1)"]:::c1
  QRN_MATTER_002["QRN-MATTER-002 (c2)"]:::c2
  QRN_COSMO_004["QRN-COSMO-004 (c1)"]:::c1
  QRN_EXP_001["QRN-EXP-001 (c4)"]:::c4
  QRN_GAUGE_003["QRN-GAUGE-003 (c2)"]:::c2
  QRN_GAUGE_004["QRN-GAUGE-004 (c1)"]:::c1
  QRN_GAUGE_005["QRN-GAUGE-005 (c4)"]:::c4
  QRN_YUK_001["QRN-YUK-001 (c4)"]:::c4
  QRN_RG_001["QRN-RG-001 (c1)"]:::c1
  QRN_UNRUH_001["QRN-UNRUH-001 (c1)"]:::c1
  QRN_QNEC_001["QRN-QNEC-001 (c1)"]:::c1
  QRN_NU_001["QRN-NU-001 (c4)"]:::c4
  QRN_GAUGE_006["QRN-GAUGE-006 (c2)"]:::c2
  QRN_DS_001["QRN-DS-001 (c1)"]:::c1
  QRN_DS_002["QRN-DS-002 (c4)"]:::c4
  QRN_ARROW_001["QRN-ARROW-001 (c3)"]:::c3
  QRN_GAUGE_007["QRN-GAUGE-007 (c2)"]:::c2
  QRN_EFT_001["QRN-EFT-001 (c1)"]:::c1
  QRN_GAUGE_008["QRN-GAUGE-008 (c2)"]:::c2
  QRN_GAUGE_009["QRN-GAUGE-009 (c2)"]:::c2
  QRN_GAUGE_010["QRN-GAUGE-010 (c2)"]:::c2
  QRN_QNEC_002["QRN-QNEC-002 (c1)"]:::c1
  QRN_GEOM_004["QRN-GEOM-004 (c3)"]:::c3
  QRN_YUK_002["QRN-YUK-002 (c4)"]:::c4
  QRN_EXP_002["QRN-EXP-002 (c5)"]:::c5
  QRN_CORE_001["QRN-CORE-001 (c3)"]:::c3
  QRN_GAUGE_011["QRN-GAUGE-011 (c2)"]:::c2
  QRN_GAUGE_012["QRN-GAUGE-012 (c2)"]:::c2
  QRN_YUK_003["QRN-YUK-003 (c4)"]:::c4
  QRN_EXP_003["QRN-EXP-003 (c4)"]:::c4
  QRN_CORE_002["QRN-CORE-002 (c3)"]:::c3
  QRN_GAUGE_013["QRN-GAUGE-013 (c2)"]:::c2
  QRN_YUK_004["QRN-YUK-004 (c4)"]:::c4
  QRN_GAUGE_014["QRN-GAUGE-014 (c2)"]:::c2
  QRN_META_001["QRN-META-001 (c5)"]:::c5
  QRN_META_002["QRN-META-002 (c5)"]:::c5
  QRN_META_003["QRN-META-003 (c5)"]:::c5
  QRN_META_004["QRN-META-004 (c5)"]:::c5
  QRN_META_005["QRN-META-005 (c5)"]:::c5
  QRN_META_006["QRN-META-006 (c5)"]:::c5
  QRN_META_007["QRN-META-007 (c5)"]:::c5
  QRN_META_008["QRN-META-008 (c5)"]:::c5
  QRN_YUK_005["QRN-YUK-005 (c4)"]:::c4
  QRN_YUK_006["QRN-YUK-006 (c4)"]:::c4
  QRN_CORE_003["QRN-CORE-003 (c1)"]:::c1
  QRN_META_009["QRN-META-009 (c5)"]:::c5
  QRN_YUK_007["QRN-YUK-007 (c4)"]:::c4
  QRN_YUK_008["QRN-YUK-008 (c4)"]:::c4
  QRN_YUK_009["QRN-YUK-009 (c2)"]:::c2
  QRN_META_010["QRN-META-010 (c5)"]:::c5
  QRN_GAUGE_015["QRN-GAUGE-015 (c2)"]:::c2
  QRN_YUK_010["QRN-YUK-010 (c3)"]:::c3
  QRN_YUK_011["QRN-YUK-011 (c4)"]:::c4
  QRN_CORE_004["QRN-CORE-004 (c3)"]:::c3
  QRN_META_011["QRN-META-011 (c5)"]:::c5
  QRN_YUK_012["QRN-YUK-012 (c3)"]:::c3
  QRN_YUK_013["QRN-YUK-013 (c4)"]:::c4
  QRN_YUK_014["QRN-YUK-014 (c4)"]:::c4
  QRN_META_012["QRN-META-012 (c5)"]:::c5
  QRN_TOOL_001["QRN-TOOL-001 (c1)"]:::c1
  QRN_YUK_015["QRN-YUK-015 (c4)"]:::c4
  QRN_META_013["QRN-META-013 (c5)"]:::c5
  QRN_GAUGE_016["QRN-GAUGE-016 (c2)"]:::c2
  QRN_GAUGE_017["QRN-GAUGE-017 (c2)"]:::c2
  QRN_META_014["QRN-META-014 (c5)"]:::c5
  QRN_META_015["QRN-META-015 (c2)"]:::c2
  QRN_TOOL_002["QRN-TOOL-002 (c2)"]:::c2
  QRN_CORE_005["QRN-CORE-005 (c3)"]:::c3
  QRN_CONT_001["QRN-CONT-001 (c1)"]:::c1
  QRN_SEL_001["QRN-SEL-001 (c4)"]:::c4
  QRN_GRAV_004["QRN-GRAV-004 (c1)"]:::c1
  QRN_PRED_001["QRN-PRED-001 (c4)"]:::c4
  QRN_META_016["QRN-META-016 (c5)"]:::c5
  QRN_YUK_016["QRN-YUK-016 (c4)"]:::c4
  QRN_YUK_017["QRN-YUK-017 (c3)"]:::c3
  QRN_YUK_018["QRN-YUK-018 (c4)"]:::c4
  QRN_YUK_019["QRN-YUK-019 (c4)"]:::c4
  QRN_YUK_020["QRN-YUK-020 (c4)"]:::c4
  QRN_YUK_021["QRN-YUK-021 (c4)"]:::c4
  QRN_YUK_022["QRN-YUK-022 (c4)"]:::c4
  QRN_YUK_023["QRN-YUK-023 (c4)"]:::c4
  QRN_YUK_024["QRN-YUK-024 (c4)"]:::c4
  QRN_YUK_025["QRN-YUK-025 (c4)"]:::c4
  QRN_SEL_002["QRN-SEL-002 (c4)"]:::c4
  QRN_SEL_003["QRN-SEL-003 (c4)"]:::c4
  QRN_SEL_004["QRN-SEL-004 (c4)"]:::c4
  QRN_META_017["QRN-META-017 (c5)"]:::c5
  QRN_YUK_026["QRN-YUK-026 (c4)"]:::c4
  QRN_YUK_027["QRN-YUK-027 (c4)"]:::c4
  QRN_MSR_001["QRN-MSR-001 (c4)"]:::c4
  QRN_MSR_002["QRN-MSR-002 (c4)"]:::c4
  QRN_MSR_003["QRN-MSR-003 (c4)"]:::c4
  QRN_YUK_028["QRN-YUK-028 (c4)"]:::c4
  QRN_YUK_029["QRN-YUK-029 (c4)"]:::c4
  QRN_YUK_030["QRN-YUK-030 (c4)"]:::c4
  QRN_META_018["QRN-META-018 (c5)"]:::c5
  QRN_YUK_031["QRN-YUK-031 (c4)"]:::c4
  QRN_LEP_001["QRN-LEP-001 (c4)"]:::c4
  QRN_LEP_002["QRN-LEP-002 (c4)"]:::c4
  QRN_LEP_003["QRN-LEP-003 (c4)"]:::c4
  QRN_LEP_004["QRN-LEP-004 (c4)"]:::c4
  QRN_LEP_005["QRN-LEP-005 (c4)"]:::c4
  QRN_META_019["QRN-META-019 (c5)"]:::c5
  QRN_GRAV_005["QRN-GRAV-005 (c2)"]:::c2
  QRN_GRAV_006["QRN-GRAV-006 (c4)"]:::c4
  QRN_GRAV_007["QRN-GRAV-007 (c2)"]:::c2
  QRN_GRAV_008["QRN-GRAV-008 (c4)"]:::c4
  QRN_GRAV_009["QRN-GRAV-009 (c2)"]:::c2
  QRN_GRAV_010["QRN-GRAV-010 (c4)"]:::c4
  QRN_GRAV_011["QRN-GRAV-011 (c2)"]:::c2
  QRN_META_020["QRN-META-020 (c5)"]:::c5
  QRN_CORE_006["QRN-CORE-006 (c2)"]:::c2
  QRN_CORE_007["QRN-CORE-007 (c4)"]:::c4
  QRN_CORE_008["QRN-CORE-008 (c2)"]:::c2
  QRN_CORE_009["QRN-CORE-009 (c4)"]:::c4
  QRN_CORE_010["QRN-CORE-010 (c2)"]:::c2
  QRN_CORE_011["QRN-CORE-011 (c2)"]:::c2
  QRN_GRAV_001 --> QRN_C0_001
  QRN_BH_001 --> QRN_C0_003
  QRN_CAUSAL_002 --> QRN_CAUSAL_001
  QRN_COSMO_002 --> QRN_COSMO_001
  QRN_COSMO_003 --> QRN_COSMO_001
  QRN_MATTER_001 --> QRN_C0_005
  QRN_MATTER_002 --> QRN_C0_005
  QRN_GAUGE_003 --> QRN_C0_005
  QRN_YUK_001 --> QRN_C0_006
  QRN_UNRUH_001 --> QRN_C0_004
  QRN_QNEC_001 --> QRN_C0_002
  QRN_NU_001 --> QRN_C0_006
  QRN_GAUGE_006 --> QRN_GAUGE_003
  QRN_DS_001 --> QRN_C0_004
  QRN_DS_002 --> QRN_DS_001
  QRN_ARROW_001 --> QRN_CAUSAL_002
  QRN_GAUGE_007 --> QRN_GAUGE_003
  QRN_GAUGE_008 --> QRN_GAUGE_003
  QRN_GAUGE_008 --> QRN_GAUGE_006
  QRN_GAUGE_008 --> QRN_GAUGE_007
  QRN_GAUGE_009 --> QRN_GAUGE_003
  QRN_GAUGE_010 --> QRN_GAUGE_006
  QRN_GAUGE_010 --> QRN_GAUGE_008
  QRN_QNEC_002 --> QRN_C0_002
  QRN_QNEC_002 --> QRN_QNEC_001
  QRN_GEOM_004 --> QRN_GEOM_003
  QRN_YUK_002 --> QRN_C0_006
  QRN_YUK_002 --> QRN_YUK_001
  QRN_EXP_002 --> QRN_EXP_001
  QRN_CORE_001 --> QRN_GEOM_003
  QRN_CORE_001 --> QRN_CAUSAL_001
  QRN_GAUGE_011 --> QRN_GAUGE_003
  QRN_YUK_003 --> QRN_C0_006
  QRN_YUK_003 --> QRN_MATTER_001
  QRN_YUK_003 --> QRN_YUK_002
  QRN_EXP_003 --> QRN_EXP_001
  QRN_CORE_002 --> QRN_CORE_001
  QRN_CORE_002 --> QRN_ER_001
  QRN_CORE_002 --> QRN_ARROW_001
  QRN_GAUGE_013 --> QRN_GAUGE_007
  QRN_YUK_004 --> QRN_YUK_003
  QRN_META_001 --> QRN_GEOM_003
  QRN_META_001 --> QRN_GRAV_001
  QRN_META_001 --> QRN_CAUSAL_001
  QRN_META_001 --> QRN_QEC_001
  QRN_META_001 --> QRN_ENT_001
  QRN_META_002 --> QRN_QEC_001
  QRN_META_002 --> QRN_BORN_001
  QRN_META_002 --> QRN_CAUSAL_002
  QRN_META_003 --> QRN_GAUGE_003
  QRN_META_003 --> QRN_RG_001
  QRN_META_003 --> QRN_QNEC_001
  QRN_META_003 --> QRN_GRAV_003
  QRN_META_004 --> QRN_META_001
  QRN_META_004 --> QRN_META_002
  QRN_META_004 --> QRN_META_003
  QRN_META_004 --> QRN_ARROW_001
  QRN_META_005 --> QRN_META_004
  QRN_META_006 --> QRN_GAUGE_008
  QRN_META_006 --> QRN_QNEC_002
  QRN_META_006 --> QRN_GEOM_004
  QRN_META_006 --> QRN_YUK_002
  QRN_META_006 --> QRN_GAUGE_011
  QRN_META_007 --> QRN_GAUGE_012
  QRN_META_007 --> QRN_YUK_003
  QRN_META_007 --> QRN_EXP_003
  QRN_META_007 --> QRN_CORE_002
  QRN_META_007 --> QRN_GAUGE_013
  QRN_META_008 --> QRN_YUK_004
  QRN_META_008 --> QRN_GAUGE_014
  QRN_YUK_005 --> QRN_YUK_004
  QRN_YUK_006 --> QRN_YUK_003
  QRN_YUK_006 --> QRN_YUK_004
  QRN_YUK_006 --> QRN_YUK_005
  QRN_CORE_003 --> QRN_QNEC_002
  QRN_META_009 --> QRN_YUK_005
  QRN_META_009 --> QRN_YUK_006
  QRN_META_009 --> QRN_CORE_003
  QRN_YUK_007 --> QRN_YUK_006
  QRN_YUK_008 --> QRN_YUK_007
  QRN_YUK_009 --> QRN_MATTER_001
  QRN_META_010 --> QRN_YUK_007
  QRN_META_010 --> QRN_YUK_008
  QRN_META_010 --> QRN_YUK_009
  QRN_GAUGE_015 --> QRN_C0_005
  QRN_GAUGE_015 --> QRN_GAUGE_014
  QRN_YUK_010 --> QRN_YUK_007
  QRN_YUK_011 --> QRN_YUK_010
  QRN_CORE_004 --> QRN_CORE_001
  QRN_CORE_004 --> QRN_CORE_002
  QRN_META_011 --> QRN_GAUGE_015
  QRN_META_011 --> QRN_YUK_010
  QRN_META_011 --> QRN_YUK_011
  QRN_META_011 --> QRN_CORE_004
  QRN_YUK_012 --> QRN_MATTER_001
  QRN_YUK_013 --> QRN_YUK_012
  QRN_YUK_013 --> QRN_YUK_007
  QRN_YUK_014 --> QRN_YUK_013
  QRN_META_012 --> QRN_YUK_012
  QRN_META_012 --> QRN_YUK_013
  QRN_META_012 --> QRN_YUK_014
  QRN_YUK_015 --> QRN_YUK_014
  QRN_YUK_015 --> QRN_TOOL_001
  QRN_YUK_015 --> QRN_YUK_009
  QRN_META_013 --> QRN_YUK_015
  QRN_META_013 --> QRN_TOOL_001
  QRN_META_013 --> QRN_YUK_009
  QRN_GAUGE_016 --> QRN_GAUGE_006
  QRN_GAUGE_017 --> QRN_GAUGE_008
  QRN_META_014 --> QRN_GAUGE_016
  QRN_META_014 --> QRN_GAUGE_017
  QRN_TOOL_002 --> QRN_META_015
  QRN_CORE_005 --> QRN_GEOM_003
  QRN_CONT_001 --> QRN_ENT_001
  QRN_SEL_001 --> QRN_YUK_007
  QRN_GRAV_004 --> QRN_C0_001
  QRN_PRED_001 --> QRN_YUK_007
  QRN_PRED_001 --> QRN_EXP_003
  QRN_META_016 --> QRN_META_015
  QRN_META_016 --> QRN_TOOL_002
  QRN_META_016 --> QRN_CORE_005
  QRN_META_016 --> QRN_CONT_001
  QRN_META_016 --> QRN_SEL_001
  QRN_META_016 --> QRN_GRAV_004
  QRN_META_016 --> QRN_PRED_001
  QRN_YUK_016 --> QRN_YUK_015
  QRN_YUK_017 --> QRN_MATTER_001
  QRN_YUK_017 --> QRN_PRED_001
  QRN_YUK_018 --> QRN_YUK_017
  QRN_YUK_018 --> QRN_YUK_007
  QRN_YUK_019 --> QRN_YUK_018
  QRN_YUK_020 --> QRN_YUK_019
  QRN_YUK_021 --> QRN_YUK_019
  QRN_YUK_022 --> QRN_YUK_019
  QRN_YUK_023 --> QRN_YUK_019
  QRN_YUK_023 --> QRN_YUK_022
  QRN_YUK_024 --> QRN_YUK_019
  QRN_YUK_024 --> QRN_YUK_023
  QRN_YUK_025 --> QRN_YUK_019
  QRN_YUK_025 --> QRN_YUK_024
  QRN_SEL_002 --> QRN_YUK_019
  QRN_SEL_002 --> QRN_YUK_024
  QRN_SEL_003 --> QRN_YUK_019
  QRN_SEL_003 --> QRN_YUK_024
  QRN_SEL_003 --> QRN_SEL_002
  QRN_SEL_004 --> QRN_YUK_019
  QRN_SEL_004 --> QRN_YUK_024
  QRN_SEL_004 --> QRN_SEL_002
  QRN_SEL_004 --> QRN_SEL_003
  QRN_META_017 --> QRN_META_016
  QRN_META_017 --> QRN_YUK_019
  QRN_META_017 --> QRN_YUK_024
  QRN_META_017 --> QRN_YUK_025
  QRN_META_017 --> QRN_SEL_002
  QRN_META_017 --> QRN_SEL_003
  QRN_META_017 --> QRN_SEL_004
  QRN_YUK_026 --> QRN_YUK_019
  QRN_YUK_026 --> QRN_YUK_024
  QRN_YUK_026 --> QRN_YUK_025
  QRN_YUK_027 --> QRN_YUK_019
  QRN_YUK_027 --> QRN_YUK_023
  QRN_YUK_027 --> QRN_YUK_024
  QRN_MSR_001 --> QRN_YUK_024
  QRN_MSR_001 --> QRN_YUK_025
  QRN_MSR_001 --> QRN_YUK_027
  QRN_MSR_002 --> QRN_SEL_004
  QRN_MSR_002 --> QRN_MSR_001
  QRN_MSR_003 --> QRN_MSR_001
  QRN_MSR_003 --> QRN_MSR_002
  QRN_MSR_003 --> QRN_SEL_004
  QRN_MSR_003 --> QRN_YUK_027
  QRN_YUK_028 --> QRN_YUK_019
  QRN_YUK_028 --> QRN_YUK_027
  QRN_YUK_029 --> QRN_YUK_028
  QRN_YUK_029 --> QRN_MSR_003
  QRN_YUK_030 --> QRN_YUK_028
  QRN_YUK_030 --> QRN_YUK_029
  QRN_META_018 --> QRN_META_017
  QRN_META_018 --> QRN_MSR_003
  QRN_META_018 --> QRN_YUK_028
  QRN_META_018 --> QRN_YUK_029
  QRN_META_018 --> QRN_YUK_030
  QRN_YUK_031 --> QRN_YUK_028
  QRN_YUK_031 --> QRN_YUK_029
  QRN_LEP_001 --> QRN_YUK_028
  QRN_LEP_001 --> QRN_YUK_029
  QRN_LEP_001 --> QRN_GAUGE_009
  QRN_LEP_002 --> QRN_LEP_001
  QRN_LEP_003 --> QRN_LEP_002
  QRN_LEP_004 --> QRN_LEP_003
  QRN_LEP_005 --> QRN_LEP_004
  QRN_META_019 --> QRN_META_018
  QRN_META_019 --> QRN_YUK_031
  QRN_META_019 --> QRN_LEP_001
  QRN_META_019 --> QRN_LEP_003
  QRN_META_019 --> QRN_LEP_004
  QRN_META_019 --> QRN_LEP_005
  QRN_GRAV_005 --> QRN_C0_002
  QRN_GRAV_005 --> QRN_GRAV_001
  QRN_GRAV_006 --> QRN_GRAV_005
  QRN_GRAV_007 --> QRN_GRAV_005
  QRN_GRAV_008 --> QRN_GRAV_006
  QRN_GRAV_009 --> QRN_GRAV_005
  QRN_GRAV_009 --> QRN_QNEC_001
  QRN_GRAV_010 --> QRN_GRAV_006
  QRN_GRAV_010 --> QRN_GRAV_008
  QRN_GRAV_011 --> QRN_GRAV_007
  QRN_META_020 --> QRN_META_019
  QRN_META_020 --> QRN_GRAV_005
  QRN_META_020 --> QRN_GRAV_006
  QRN_META_020 --> QRN_GRAV_007
  QRN_META_020 --> QRN_GRAV_008
  QRN_META_020 --> QRN_GRAV_009
  QRN_META_020 --> QRN_GRAV_010
  QRN_META_020 --> QRN_GRAV_011
  QRN_CORE_007 --> QRN_CORE_006
  QRN_CORE_008 --> QRN_CORE_006
  QRN_CORE_009 --> QRN_CORE_006
  QRN_CORE_010 --> QRN_CORE_006
  QRN_CORE_011 --> QRN_CORE_010
  classDef c0 fill:#bdbdbd
  classDef c1 fill:#7cb342
  classDef c2 fill:#1e88e5
  classDef c3 fill:#fb8c00
  classDef c4 fill:#fdd835
  classDef c5 fill:#e53935
